config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/top' => 'homes#top'
  root to: 'homes#top'  #アプリケーショントップ画面をルートパスに設定

  resources :books  #resources メソッド

  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'


end

#GET    データの取得(ページ自体もデータ)
#POST   新しいデータの作成
#PUT    既存のデータの更新
#PATCH  既存のデータの一部更新
#DELETE 既存のデータを削除

#                        Prefix Verb   URI Pattern                    Controller#Action
  #                         top GET    /top(.:format)                 homes#top
  #                        root GET    /                              homes#top
   #                      books GET    /books(.:format)               books#index
   #                            POST   /books(.:format)               books#create
   #                   new_book GET    /books/new(.:format)           books#new
   #                  edit_book GET    /books/:id/edit(.:format)      books#edit
   #                       book GET    /books/:id(.:format)           books#show
   #                            PATCH  /books/:id(.:format)           books#update
   #                            PUT    /books/:id(.:format)           books#update
   #                            DELETE /books/:id(.:format)           books#destroy
   #                update_book PATCH  /books/:id(.:format)           books#update
   #               destroy_book DELETE /books/:id(.:format)           books#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  #データの新規作成フォームを表示する
  def new
    @book = Book.new
  end

  #データを追加（保存）する
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  #データの一覧を表示する
  def index
    @book = Book.new
    @books = Book.all
  end

  #データの内容（詳細）を表示する
  def show
    @book = Book.find(params[:id])
  end

  #データを更新するためのフォームを表示する
  def edit
    @book = Book.find(params[:id])
  end

  #データを更新する
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  #データを削除する
  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to '/books'
  end

  private
  #　ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<!-- エラーメッセージ -->
<div class="error-box">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
    <div class="error-message">
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<!-- 投稿編集 -->
<div class="field">
  <%= form_with model: @book do |f| %>
    <div class="form">
      <label>Title</label>
      <div class="input-box">
        <%= f.text_field :title %>
      </div>
    </div>

    <div class="form">
      <label>Body</label>
      <div class="input-box">
        <%= f.text_area :body %>
      </div>
    </div>

    <div class="form">
      <%= f.submit 'Update Book', class: 'submit-btn' %>
    </div>
  <% end %>
</div>

<!-- リンク -->
<%= link_to 'Show', book_path(@book), class: "show_link" %>
|
<%= link_to 'Back', '/books', class: "back_link" %>

app/views/books/index.html.erb
<!-- フラッシュメッセージ表示 -->
<div>
  <p class="notice"><%= flash[:notice] %></p>
</div>

<h1 class="main-title">Books</h1>

<!-- 投稿一覧表示 -->
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @books.each do |list| %>
    <tr>
      <td><%= list.title %></td>
      <td><%= list.body %></td>
      <!-- Showへのリンク -->
      <td>
        <%= link_to 'Show', book_path(list.id) %>
      </td>
      <!-- Editへのリンク -->
      <td>
        <%= link_to 'Edit', edit_book_path(list.id) %>
      </td>
      <!-- Destroyへのリンク -->
      <td>
        <%= link_to 'Destroy', destroy_book_path(list.id), method: :delete, "data-confirm" => "Are you sure?" %>
      </td>
    </tr>
  <% end %>
</table>

<!-- 新規投稿部分 -->
<h2 class="sub-title">New book</h2>

<!-- エラーメッセージ -->
<div class="error-box">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
    <div class="error-message">
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<!-- 投稿部分 -->
<div class="field">
  <%= form_with model: @book do |f| %>
    <div class="form">
      <label>Title</label>
      <div class="input-box">
        <%= f.text_field :title %>
      </div>
    </div>

    <div class="form">
      <label>Body</label>
      <div class="input-box">
        <%= f.text_area :body %>
      </div>
    </div>

    <div class="form">
      <%= f.submit 'Create Book', class: 'submit-btn' %>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<!-- フラッシュメッセージ表示 -->
<div>
  <p class="notice"><%= flash[:notice] %></p>
</div>

<!-- 投稿詳細表示 -->
<p class="edit-title">
  <b>Title: </b><%= @book.title %>
</p>
<p class="edit-body">
  <b>Body: </b><%= @book.body %>
</p>

<!-- リンク -->
<%= link_to "Edit", edit_book_path(@book), class: "edit_link" %>
|
<%= link_to "Back", '/books', class: "back_link" %>

app/views/homes/top.html.erb
<h1 class="top-title">ようこそ Bookers へ！</h1>
<p><b>Bookers</b> では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p>
  <a><%= link_to 'start', '/books' %></a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>